# Generated by Django 2.2.2 on 2019-07-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp704', max_length=70),
        ),
    ]
