# Generated by Django 2.2.2 on 2019-07-12 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp397', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 14, 53, 45, 853717, tzinfo=utc)),
        ),
    ]
