# Generated by Django 2.2.2 on 2019-09-30 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_auto_20190930_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp174', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 14, 11, 33, 979989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end',
            field=models.DateField(max_length=15),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start',
            field=models.DateField(max_length=15),
        ),
    ]
