# Generated by Django 2.2.2 on 2019-07-23 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_auto_20190723_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp355', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 11, 53, 14, 711273, tzinfo=utc)),
        ),
    ]
