# Generated by Django 2.2.2 on 2019-07-08 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_employee_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp372', max_length=70),
        ),
    ]
