# Generated by Django 2.2.2 on 2019-07-23 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_auto_20190723_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.CharField(default='00,000.00', max_length=16),
        ),
        migrations.AlterField(
            model_name='department',
            name='history',
            field=models.TextField(blank=True, default='No History', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp717', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 14, 14, 16, 97885, tzinfo=utc)),
        ),
    ]
