# Generated by Django 2.2.2 on 2019-10-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_auto_20191002_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank',
            field=models.CharField(default='First Bank Plc', max_length=25),
        ),
        migrations.AddField(
            model_name='employee',
            name='nuban',
            field=models.CharField(default='0123456789', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp821', max_length=70, unique=True),
        ),
    ]
