# Generated by Django 2.2.2 on 2019-07-09 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_auto_20190708_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp722', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 9, 50, 40, 766035, tzinfo=utc)),
        ),
    ]
