# Generated by Django 2.2.2 on 2019-07-14 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_auto_20190712_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='first_in',
            field=models.TimeField(verbose_name=1563115379.4017553),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='last_out',
            field=models.TimeField(verbose_name=1563115379.4017785),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp847', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 14, 42, 59, 399958, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='thumb',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='Kin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=100)),
                ('occupation', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hrms.Employee')),
            ],
        ),
    ]
