# Generated by Django 2.2.2 on 2019-07-19 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_auto_20190714_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='history',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='first_in',
            field=models.TimeField(verbose_name=1563533866.8912334),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='last_out',
            field=models.TimeField(verbose_name=1563533866.891256),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp427', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 10, 57, 46, 889547, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
