# Generated by Django 2.2.2 on 2019-07-19 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_auto_20190719_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='first_in',
            field=models.TimeField(verbose_name=1563533897.8537717),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='last_out',
            field=models.TimeField(verbose_name=1563533897.8537939),
        ),
        migrations.AlterField(
            model_name='department',
            name='history',
            field=models.TextField(blank=True, default='No History', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp961', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 10, 58, 17, 852100, tzinfo=utc)),
        ),
    ]
